[package]
name = "escrowenclave"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "escrowenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tcrypto = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tseal = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_trts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net"] }
sgx_rand = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }


[dependencies]
serde = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_cbor = { git = "https://github.com/mesalock-linux/cbor-sgx" }
libsecp256k1 = { git ="https://github.com/mesalock-linux/libsecp256k1-rs-sgx"}
rustls = { git = "https://github.com/mesalock-linux/rustls", branch = "mesalock_sgx" }
webpki = { git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx" }
lazy_static = { version = "1.4.0", default-features = false, features = ["spin_no_std"] }
rand = { git = "https://github.com/mesalock-linux/rand-sgx", tag = "v0.6.5_sgx1.1.1" }


[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_alloc = { path = "../../dependencies/sgx_alloc" }
sgx_backtrace = { path = "../../dependencies/sgx_backtrace" }
sgx_backtrace_sys = { path = "../../dependencies/sgx_backtrace_sys" }
sgx_build_helper = { path = "../../dependencies/sgx_build_helper" }
sgx_cov = { path = "../../dependencies/sgx_cov" }
sgx_crypto_helper = { path = "../../dependencies/sgx_crypto_helper" }
sgx_demangle = { path = "../../dependencies/sgx_demangle" }
sgx_libc = { path = "../../dependencies/sgx_libc" }
sgx_rand = { path = "../../dependencies/sgx_rand" }
sgx_rand_derive = { path = "../../dependencies/sgx_rand_derive" }
sgx_serialize = { path = "../../dependencies/sgx_serialize" }
sgx_serialize_derive = { path = "../../dependencies/sgx_serialize_derive" }
sgx_serialize_derive_internals = { path = "../../dependencies/sgx_serialize_derive_internals" }
sgx_tcrypto = { path = "../../dependencies/sgx_tcrypto" }
sgx_tcrypto_helper = { path = "../../dependencies/sgx_tcrypto_helper" }
sgx_tdh = { path = "../../dependencies/sgx_tdh" }
sgx_tkey_exchange = { path = "../../dependencies/sgx_tkey_exchange" }
sgx_tprotected_fs = { path = "../../dependencies/sgx_tprotected_fs" }
sgx_trts = { path = "../../dependencies/sgx_trts" }
sgx_tse = { path = "../../dependencies/sgx_tse" }
sgx_tseal = { path = "../../dependencies/sgx_tseal" }
sgx_tstd = { path = "../../dependencies/sgx_tstd" }
sgx_tunittest = { path = "../../dependencies/sgx_tunittest" }
sgx_types = { path = "../../dependencies/sgx_types" }
#sgx_ucrypto = { path = "../../dependencies/sgx_ucrypto" }
sgx_unwind = { path = "../../dependencies/sgx_unwind" }
#sgx_urts = { path = "../../dependencies/sgx_urts" }

